/** PERSON 3 – Kartenübersicht und Zugang zum Editor/Lernmodus. */
import { api } from '../api.js';
import { escapeHtml as e, icon, subjectLook, pluralCards, dueLabel, confirmDelete } from './ui.js';
import { openDeckEditor } from './DeckEditor.js';
import { openCardEditor } from './CardEditor.js';

export function renderDeckView(container, { deck, cards }, refresh) {
  const look = subjectLook(deck.subject);
  container.innerHTML = `<a href="#/decks" class="back-link">${icon('back')}Alle Kartendecks</a><div class="page-heading deck-page-heading"><div><span class="eyebrow">${e(deck.subject)}</span><h1>${e(deck.name)}</h1><p>${e(deck.description)}</p></div><div class="button-group"><button class="button secondary" id="edit-deck">${icon('edit')}Deck bearbeiten</button><button class="icon-button delete-deck" id="delete-deck" aria-label="Deck löschen">${icon('trash')}</button></div></div>
  <section class="deck-summary ${look.theme}"><div class="deck-summary-icon">${icon(look.icon)}</div><div class="deck-numbers"><strong>${cards.length}</strong><span>Karten im Deck</span></div><div class="deck-numbers"><strong>${deck.dueCount}</strong><span>jetzt fällig</span></div><div class="summary-progress"><div><strong>${deck.progress} %</strong><span>Lernfortschritt</span></div><progress value="${deck.progress}" max="100" aria-label="Lernfortschritt">${deck.progress}%</progress></div><div class="deck-study-actions">${cards.length ? `<a class="button primary" href="#/study/${deck.id}${deck.dueCount ? '' : '?all=1'}">${icon('play')}${deck.dueCount ? 'Fällige Karten lernen' : 'Alle Karten üben'}</a>${deck.dueCount && deck.dueCount < cards.length ? `<a class="text-link" href="#/study/${deck.id}?all=1">Alle Karten üben</a>` : ''}` : '<span>Füge deine erste Karte hinzu.</span>'}</div></section>
  <section><div class="section-heading"><div><h2>Deine Karten <span class="count-pill">${cards.length}</span></h2><p>Fragen stellen. Antworten festhalten.</p></div><button class="button primary" id="new-card">${icon('plus')}Neue Karte</button></div>${cards.length ? `<div class="card-list">${cards.map((card, index) => `<article class="card-row"><span class="card-number">${String(index + 1).padStart(2, '0')}</span><div class="card-row-content"><h3>${e(card.front)}</h3><p>${e(card.back)}</p><div class="card-meta"><span>${e(dueLabel(card))}</span><span>${card.score} % Sicherheit</span>${card.images.length ? `<span>${icon('image')}${card.images.length} ${card.images.length === 1 ? 'Bild' : 'Bilder'}</span>` : ''}</div></div><div class="card-row-actions"><button class="icon-button edit-card" data-id="${card.id}" aria-label="Karte ${index + 1} bearbeiten">${icon('edit')}</button><button class="icon-button delete-card" data-id="${card.id}" aria-label="Karte ${index + 1} löschen">${icon('trash')}</button></div></article>`).join('')}</div>` : `<div class="empty-state"><span class="empty-icon">${icon('book')}</span><h3>Welche Frage möchtest du dir merken?</h3><p>Schreibe eine Frage auf die Vorderseite und die Antwort auf die Rückseite.<br>Bei Bedarf kannst du beiden Seiten Bilder hinzufügen.</p><button class="button primary" id="first-card">${icon('plus')}Erste Karte erstellen</button></div>`}</section>`;
  container.querySelector('#edit-deck').onclick = () => openDeckEditor(deck, refresh);
  container.querySelector('#delete-deck').onclick = () => confirmDelete('Ganzes Deck löschen?', `„${deck.name}“ und ${pluralCards(cards.length)} einschließlich Bildern und Lernständen werden endgültig gelöscht.`, () => api.deleteDeck(deck.id), () => { location.hash = '#/decks'; });
  container.querySelectorAll('#new-card,#first-card').forEach((button) => { button.onclick = () => openCardEditor(deck.id, null, refresh); });
  container.querySelectorAll('.edit-card').forEach((button) => { button.onclick = () => openCardEditor(deck.id, cards.find((card) => card.id === button.dataset.id), refresh); });
  container.querySelectorAll('.delete-card').forEach((button) => { button.onclick = () => confirmDelete('Karte löschen?', 'Die Karte, ihre Bilder und ihr Lernstand werden endgültig gelöscht.', () => api.deleteCard(button.dataset.id), refresh); });
}
