// Platzhalter-Daten: 5 Restaurants pro Bezirk (Wien, 1.–23. Bezirk) = 115 Restaurants
// rating: Fake-Bewertung von 0–5 Sternen
// adresse: erfundene Adresse (echte Straßennamen, erfundene Hausnummern)
// oeffnung: tägliche Öffnungszeit von/bis ("bis" vor "von" = geht über Mitternacht)
const restaurants = [
  // 1. Bezirk
  { name: "Trattoria Stephansplatz", kueche: "Italienisch", preis: "$", bezirk: 1,
    adresse: "Graben 8, 1010 Wien",
    rating: 3.4, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Stephansplatz", kueche: "Italienisch", preis: "$$", bezirk: 1,
    adresse: "Kärntner Straße 19, 1010 Wien",
    rating: 3.7, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Stephansplatz", kueche: "Italienisch", preis: "$$$", bezirk: 1,
    adresse: "Wollzeile 30, 1010 Wien",
    rating: 4.0, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Lotus Stephansplatz", kueche: "Chinesisch", preis: "$$", bezirk: 1,
    adresse: "Rotenturmstraße 41, 1010 Wien",
    rating: 4.3, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Bambus Stephansplatz", kueche: "Chinesisch", preis: "$$$", bezirk: 1,
    adresse: "Bäckerstraße 52, 1010 Wien",
    rating: 4.6, oeffnung: { von: "11:00", bis: "00:00" } },
  // 2. Bezirk
  { name: "Trattoria Prater", kueche: "Italienisch", preis: "$", bezirk: 2,
    adresse: "Praterstraße 15, 1020 Wien",
    rating: 4.9, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Prater", kueche: "Italienisch", preis: "$$", bezirk: 2,
    adresse: "Taborstraße 26, 1020 Wien",
    rating: 3.5, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Prater", kueche: "Italienisch", preis: "$$$", bezirk: 2,
    adresse: "Czerningasse 37, 1020 Wien",
    rating: 3.8, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Jadegarten Prater", kueche: "Chinesisch", preis: "$", bezirk: 2,
    adresse: "Vorgartenstraße 48, 1020 Wien",
    rating: 4.1, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Kaiserpalast Prater", kueche: "Chinesisch", preis: "$$$", bezirk: 2,
    adresse: "Heinestraße 59, 1020 Wien",
    rating: 4.4, oeffnung: { von: "11:00", bis: "00:00" } },
  // 3. Bezirk
  { name: "Trattoria Belvedere", kueche: "Italienisch", preis: "$", bezirk: 3,
    adresse: "Landstraßer Hauptstraße 22, 1030 Wien",
    rating: 4.7, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Belvedere", kueche: "Italienisch", preis: "$$", bezirk: 3,
    adresse: "Rochusgasse 33, 1030 Wien",
    rating: 5.0, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Belvedere", kueche: "Italienisch", preis: "$$$", bezirk: 3,
    adresse: "Ungargasse 44, 1030 Wien",
    rating: 3.6, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Goldener Drache Belvedere", kueche: "Chinesisch", preis: "$", bezirk: 3,
    adresse: "Erdbergstraße 55, 1030 Wien",
    rating: 3.9, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Peking Belvedere", kueche: "Chinesisch", preis: "$$", bezirk: 3,
    adresse: "Rennweg 6, 1030 Wien",
    rating: 4.2, oeffnung: { von: "11:00", bis: "00:00" } },
  // 4. Bezirk
  { name: "Trattoria Karlsplatz", kueche: "Italienisch", preis: "$", bezirk: 4,
    adresse: "Schleifmühlgasse 29, 1040 Wien",
    rating: 4.5, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Karlsplatz", kueche: "Italienisch", preis: "$$", bezirk: 4,
    adresse: "Rubensgasse 40, 1040 Wien",
    rating: 4.8, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Karlsplatz", kueche: "Italienisch", preis: "$$$", bezirk: 4,
    adresse: "Schaumburgergasse 51, 1040 Wien",
    rating: 3.4, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Bambus Karlsplatz", kueche: "Chinesisch", preis: "$$", bezirk: 4,
    adresse: "Wiedner Hauptstraße 2, 1040 Wien",
    rating: 3.7, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Lotus Karlsplatz", kueche: "Chinesisch", preis: "$$$", bezirk: 4,
    adresse: "Favoritenstraße 13, 1040 Wien",
    rating: 4.0, oeffnung: { von: "11:00", bis: "00:00" } },
  // 5. Bezirk
  { name: "Trattoria Margaretenplatz", kueche: "Italienisch", preis: "$", bezirk: 5,
    adresse: "Margaretenstraße 36, 1050 Wien",
    rating: 4.3, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Margaretenplatz", kueche: "Italienisch", preis: "$$", bezirk: 5,
    adresse: "Reinprechtsdorfer Straße 47, 1050 Wien",
    rating: 4.6, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Margaretenplatz", kueche: "Italienisch", preis: "$$$", bezirk: 5,
    adresse: "Schönbrunner Straße 58, 1050 Wien",
    rating: 4.9, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Kaiserpalast Margaretenplatz", kueche: "Chinesisch", preis: "$", bezirk: 5,
    adresse: "Siebenbrunnengasse 9, 1050 Wien",
    rating: 3.5, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Jadegarten Margaretenplatz", kueche: "Chinesisch", preis: "$$$", bezirk: 5,
    adresse: "Arbeitergasse 20, 1050 Wien",
    rating: 3.8, oeffnung: { von: "11:00", bis: "00:00" } },
  // 6. Bezirk
  { name: "Trattoria Naschmarkt", kueche: "Italienisch", preis: "$", bezirk: 6,
    adresse: "Mariahilfer Straße 43, 1060 Wien",
    rating: 4.1, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Naschmarkt", kueche: "Italienisch", preis: "$$", bezirk: 6,
    adresse: "Gumpendorfer Straße 54, 1060 Wien",
    rating: 4.4, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Naschmarkt", kueche: "Italienisch", preis: "$$$", bezirk: 6,
    adresse: "Linke Wienzeile 5, 1060 Wien",
    rating: 4.7, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Peking Naschmarkt", kueche: "Chinesisch", preis: "$", bezirk: 6,
    adresse: "Königsklostergasse 16, 1060 Wien",
    rating: 5.0, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Goldener Drache Naschmarkt", kueche: "Chinesisch", preis: "$$", bezirk: 6,
    adresse: "Webgasse 27, 1060 Wien",
    rating: 3.6, oeffnung: { von: "11:00", bis: "00:00" } },
  // 7. Bezirk
  { name: "Trattoria Spittelberg", kueche: "Italienisch", preis: "$", bezirk: 7,
    adresse: "Neubaugasse 50, 1070 Wien",
    rating: 3.9, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Spittelberg", kueche: "Italienisch", preis: "$$", bezirk: 7,
    adresse: "Burggasse 1, 1070 Wien",
    rating: 4.2, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Spittelberg", kueche: "Italienisch", preis: "$$$", bezirk: 7,
    adresse: "Siebensterngasse 12, 1070 Wien",
    rating: 4.5, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Lotus Spittelberg", kueche: "Chinesisch", preis: "$$", bezirk: 7,
    adresse: "Kaiserstraße 23, 1070 Wien",
    rating: 4.8, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Bambus Spittelberg", kueche: "Chinesisch", preis: "$$$", bezirk: 7,
    adresse: "Westbahnstraße 34, 1070 Wien",
    rating: 3.4, oeffnung: { von: "11:00", bis: "00:00" } },
  // 8. Bezirk
  { name: "Trattoria Piaristen", kueche: "Italienisch", preis: "$", bezirk: 8,
    adresse: "Josefstädter Straße 57, 1080 Wien",
    rating: 3.7, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Piaristen", kueche: "Italienisch", preis: "$$", bezirk: 8,
    adresse: "Lange Gasse 8, 1080 Wien",
    rating: 4.0, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Piaristen", kueche: "Italienisch", preis: "$$$", bezirk: 8,
    adresse: "Laudongasse 19, 1080 Wien",
    rating: 4.3, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Jadegarten Piaristen", kueche: "Chinesisch", preis: "$", bezirk: 8,
    adresse: "Alser Straße 30, 1080 Wien",
    rating: 4.6, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Kaiserpalast Piaristen", kueche: "Chinesisch", preis: "$$$", bezirk: 8,
    adresse: "Skodagasse 41, 1080 Wien",
    rating: 4.9, oeffnung: { von: "11:00", bis: "00:00" } },
  // 9. Bezirk
  { name: "Trattoria Servitenviertel", kueche: "Italienisch", preis: "$", bezirk: 9,
    adresse: "Währinger Straße 4, 1090 Wien",
    rating: 3.5, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Servitenviertel", kueche: "Italienisch", preis: "$$", bezirk: 9,
    adresse: "Servitengasse 15, 1090 Wien",
    rating: 3.8, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Servitenviertel", kueche: "Italienisch", preis: "$$$", bezirk: 9,
    adresse: "Porzellangasse 26, 1090 Wien",
    rating: 4.1, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Goldener Drache Servitenviertel", kueche: "Chinesisch", preis: "$", bezirk: 9,
    adresse: "Liechtensteinstraße 37, 1090 Wien",
    rating: 4.4, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Peking Servitenviertel", kueche: "Chinesisch", preis: "$$", bezirk: 9,
    adresse: "Nußdorfer Straße 48, 1090 Wien",
    rating: 4.7, oeffnung: { von: "11:00", bis: "00:00" } },
  // 10. Bezirk
  { name: "Trattoria Reumannplatz", kueche: "Italienisch", preis: "$", bezirk: 10,
    adresse: "Favoritenstraße 11, 1100 Wien",
    rating: 5.0, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Reumannplatz", kueche: "Italienisch", preis: "$$", bezirk: 10,
    adresse: "Quellenstraße 22, 1100 Wien",
    rating: 3.6, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Reumannplatz", kueche: "Italienisch", preis: "$$$", bezirk: 10,
    adresse: "Triester Straße 33, 1100 Wien",
    rating: 3.9, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Bambus Reumannplatz", kueche: "Chinesisch", preis: "$$", bezirk: 10,
    adresse: "Laaer-Berg-Straße 44, 1100 Wien",
    rating: 4.2, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Lotus Reumannplatz", kueche: "Chinesisch", preis: "$$$", bezirk: 10,
    adresse: "Absberggasse 55, 1100 Wien",
    rating: 4.5, oeffnung: { von: "11:00", bis: "00:00" } },
  // 11. Bezirk
  { name: "Trattoria Gasometer", kueche: "Italienisch", preis: "$", bezirk: 11,
    adresse: "Simmeringer Hauptstraße 18, 1110 Wien",
    rating: 4.8, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Gasometer", kueche: "Italienisch", preis: "$$", bezirk: 11,
    adresse: "Enkplatz 29, 1110 Wien",
    rating: 3.4, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Gasometer", kueche: "Italienisch", preis: "$$$", bezirk: 11,
    adresse: "Geiselbergstraße 40, 1110 Wien",
    rating: 3.7, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Kaiserpalast Gasometer", kueche: "Chinesisch", preis: "$", bezirk: 11,
    adresse: "Braunhubergasse 51, 1110 Wien",
    rating: 4.0, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Jadegarten Gasometer", kueche: "Chinesisch", preis: "$$$", bezirk: 11,
    adresse: "Kaiser-Ebersdorfer Straße 2, 1110 Wien",
    rating: 4.3, oeffnung: { von: "11:00", bis: "00:00" } },
  // 12. Bezirk
  { name: "Trattoria Meidlinger Markt", kueche: "Italienisch", preis: "$", bezirk: 12,
    adresse: "Meidlinger Hauptstraße 25, 1120 Wien",
    rating: 4.6, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Meidlinger Markt", kueche: "Italienisch", preis: "$$", bezirk: 12,
    adresse: "Schönbrunner Straße 36, 1120 Wien",
    rating: 4.9, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Meidlinger Markt", kueche: "Italienisch", preis: "$$$", bezirk: 12,
    adresse: "Hetzendorfer Straße 47, 1120 Wien",
    rating: 3.5, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Peking Meidlinger Markt", kueche: "Chinesisch", preis: "$", bezirk: 12,
    adresse: "Rosaliagasse 58, 1120 Wien",
    rating: 3.8, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Goldener Drache Meidlinger Markt", kueche: "Chinesisch", preis: "$$", bezirk: 12,
    adresse: "Längenfeldgasse 9, 1120 Wien",
    rating: 4.1, oeffnung: { von: "11:00", bis: "00:00" } },
  // 13. Bezirk
  { name: "Trattoria Schönbrunn", kueche: "Italienisch", preis: "$", bezirk: 13,
    adresse: "Hietzinger Hauptstraße 32, 1130 Wien",
    rating: 4.4, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Schönbrunn", kueche: "Italienisch", preis: "$$", bezirk: 13,
    adresse: "Lainzer Straße 43, 1130 Wien",
    rating: 4.7, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Schönbrunn", kueche: "Italienisch", preis: "$$$", bezirk: 13,
    adresse: "Auhofstraße 54, 1130 Wien",
    rating: 5.0, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Lotus Schönbrunn", kueche: "Chinesisch", preis: "$$", bezirk: 13,
    adresse: "Fasangartengasse 5, 1130 Wien",
    rating: 3.6, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Bambus Schönbrunn", kueche: "Chinesisch", preis: "$$$", bezirk: 13,
    adresse: "Trauttmansdorffgasse 16, 1130 Wien",
    rating: 3.9, oeffnung: { von: "11:00", bis: "00:00" } },
  // 14. Bezirk
  { name: "Trattoria Hütteldorf", kueche: "Italienisch", preis: "$", bezirk: 14,
    adresse: "Penzinger Straße 39, 1140 Wien",
    rating: 4.2, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Hütteldorf", kueche: "Italienisch", preis: "$$", bezirk: 14,
    adresse: "Hütteldorfer Straße 50, 1140 Wien",
    rating: 4.5, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Hütteldorf", kueche: "Italienisch", preis: "$$$", bezirk: 14,
    adresse: "Linzer Straße 1, 1140 Wien",
    rating: 4.8, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Jadegarten Hütteldorf", kueche: "Chinesisch", preis: "$", bezirk: 14,
    adresse: "Hadikgasse 12, 1140 Wien",
    rating: 3.4, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Kaiserpalast Hütteldorf", kueche: "Chinesisch", preis: "$$$", bezirk: 14,
    adresse: "Märzstraße 23, 1140 Wien",
    rating: 3.7, oeffnung: { von: "11:00", bis: "00:00" } },
  // 15. Bezirk
  { name: "Trattoria Westbahnhof", kueche: "Italienisch", preis: "$", bezirk: 15,
    adresse: "Mariahilfer Straße 46, 1150 Wien",
    rating: 4.0, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Westbahnhof", kueche: "Italienisch", preis: "$$", bezirk: 15,
    adresse: "Felberstraße 57, 1150 Wien",
    rating: 4.3, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Westbahnhof", kueche: "Italienisch", preis: "$$$", bezirk: 15,
    adresse: "Sechshauser Straße 8, 1150 Wien",
    rating: 4.6, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Goldener Drache Westbahnhof", kueche: "Chinesisch", preis: "$", bezirk: 15,
    adresse: "Reindorfgasse 19, 1150 Wien",
    rating: 4.9, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Peking Westbahnhof", kueche: "Chinesisch", preis: "$$", bezirk: 15,
    adresse: "Gablenzgasse 30, 1150 Wien",
    rating: 3.5, oeffnung: { von: "11:00", bis: "00:00" } },
  // 16. Bezirk
  { name: "Trattoria Brunnenmarkt", kueche: "Italienisch", preis: "$", bezirk: 16,
    adresse: "Thaliastraße 53, 1160 Wien",
    rating: 3.8, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Brunnenmarkt", kueche: "Italienisch", preis: "$$", bezirk: 16,
    adresse: "Ottakringer Straße 4, 1160 Wien",
    rating: 4.1, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Brunnenmarkt", kueche: "Italienisch", preis: "$$$", bezirk: 16,
    adresse: "Koppstraße 15, 1160 Wien",
    rating: 4.4, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Bambus Brunnenmarkt", kueche: "Chinesisch", preis: "$$", bezirk: 16,
    adresse: "Hasnerstraße 26, 1160 Wien",
    rating: 4.7, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Lotus Brunnenmarkt", kueche: "Chinesisch", preis: "$$$", bezirk: 16,
    adresse: "Brunnengasse 37, 1160 Wien",
    rating: 5.0, oeffnung: { von: "11:00", bis: "00:00" } },
  // 17. Bezirk
  { name: "Trattoria Schwarzenberg", kueche: "Italienisch", preis: "$", bezirk: 17,
    adresse: "Hernalser Hauptstraße 60, 1170 Wien",
    rating: 3.6, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Schwarzenberg", kueche: "Italienisch", preis: "$$", bezirk: 17,
    adresse: "Jörgerstraße 11, 1170 Wien",
    rating: 3.9, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Schwarzenberg", kueche: "Italienisch", preis: "$$$", bezirk: 17,
    adresse: "Rosensteingasse 22, 1170 Wien",
    rating: 4.2, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Kaiserpalast Schwarzenberg", kueche: "Chinesisch", preis: "$", bezirk: 17,
    adresse: "Dornbacher Straße 33, 1170 Wien",
    rating: 4.5, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Jadegarten Schwarzenberg", kueche: "Chinesisch", preis: "$$$", bezirk: 17,
    adresse: "Kalvarienberggasse 44, 1170 Wien",
    rating: 4.8, oeffnung: { von: "11:00", bis: "00:00" } },
  // 18. Bezirk
  { name: "Trattoria Türkenschanze", kueche: "Italienisch", preis: "$", bezirk: 18,
    adresse: "Währinger Straße 7, 1180 Wien",
    rating: 3.4, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Türkenschanze", kueche: "Italienisch", preis: "$$", bezirk: 18,
    adresse: "Gentzgasse 18, 1180 Wien",
    rating: 3.7, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Türkenschanze", kueche: "Italienisch", preis: "$$$", bezirk: 18,
    adresse: "Kutschkergasse 29, 1180 Wien",
    rating: 4.0, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Peking Türkenschanze", kueche: "Chinesisch", preis: "$", bezirk: 18,
    adresse: "Antonigasse 40, 1180 Wien",
    rating: 4.3, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Goldener Drache Türkenschanze", kueche: "Chinesisch", preis: "$$", bezirk: 18,
    adresse: "Cottagegasse 51, 1180 Wien",
    rating: 4.6, oeffnung: { von: "11:00", bis: "00:00" } },
  // 19. Bezirk
  { name: "Trattoria Grinzing", kueche: "Italienisch", preis: "$", bezirk: 19,
    adresse: "Döblinger Hauptstraße 14, 1190 Wien",
    rating: 4.9, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Grinzing", kueche: "Italienisch", preis: "$$", bezirk: 19,
    adresse: "Grinzinger Allee 25, 1190 Wien",
    rating: 3.5, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Grinzing", kueche: "Italienisch", preis: "$$$", bezirk: 19,
    adresse: "Billrothstraße 36, 1190 Wien",
    rating: 3.8, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Lotus Grinzing", kueche: "Chinesisch", preis: "$$", bezirk: 19,
    adresse: "Sieveringer Straße 47, 1190 Wien",
    rating: 4.1, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Bambus Grinzing", kueche: "Chinesisch", preis: "$$$", bezirk: 19,
    adresse: "Heiligenstädter Straße 58, 1190 Wien",
    rating: 4.4, oeffnung: { von: "11:00", bis: "00:00" } },
  // 20. Bezirk
  { name: "Trattoria Brigittenau", kueche: "Italienisch", preis: "$", bezirk: 20,
    adresse: "Brigittenauer Lände 21, 1200 Wien",
    rating: 4.7, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Augarten", kueche: "Italienisch", preis: "$$", bezirk: 20,
    adresse: "Jägerstraße 32, 1200 Wien",
    rating: 5.0, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Donaublick", kueche: "Italienisch", preis: "$$$", bezirk: 20,
    adresse: "Wallensteinstraße 43, 1200 Wien",
    rating: 3.6, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Goldener Drache", kueche: "Chinesisch", preis: "$", bezirk: 20,
    adresse: "Dresdner Straße 54, 1200 Wien",
    rating: 3.9, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Jadegarten", kueche: "Chinesisch", preis: "$$", bezirk: 20,
    adresse: "Rauscherstraße 5, 1200 Wien",
    rating: 4.2, oeffnung: { von: "11:00", bis: "00:00" } },
  // 21. Bezirk
  { name: "Trattoria Floridsdorf", kueche: "Italienisch", preis: "$", bezirk: 21,
    adresse: "Floridsdorfer Hauptstraße 28, 1210 Wien",
    rating: 4.5, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Floridsdorf", kueche: "Italienisch", preis: "$$", bezirk: 21,
    adresse: "Prager Straße 39, 1210 Wien",
    rating: 4.8, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Floridsdorf", kueche: "Italienisch", preis: "$$$", bezirk: 21,
    adresse: "Schloßhofer Straße 50, 1210 Wien",
    rating: 3.4, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Goldener Drache Floridsdorf", kueche: "Chinesisch", preis: "$", bezirk: 21,
    adresse: "Brünner Straße 1, 1210 Wien",
    rating: 3.7, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Peking Floridsdorf", kueche: "Chinesisch", preis: "$$", bezirk: 21,
    adresse: "Angererstraße 12, 1210 Wien",
    rating: 4.0, oeffnung: { von: "11:00", bis: "00:00" } },
  // 22. Bezirk
  { name: "Trattoria Donaucity", kueche: "Italienisch", preis: "$", bezirk: 22,
    adresse: "Wagramer Straße 35, 1220 Wien",
    rating: 4.3, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Donaucity", kueche: "Italienisch", preis: "$$", bezirk: 22,
    adresse: "Donaustadtstraße 46, 1220 Wien",
    rating: 4.6, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Donaucity", kueche: "Italienisch", preis: "$$$", bezirk: 22,
    adresse: "Langobardenstraße 57, 1220 Wien",
    rating: 4.9, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Bambus Donaucity", kueche: "Chinesisch", preis: "$$", bezirk: 22,
    adresse: "Erzherzog-Karl-Straße 8, 1220 Wien",
    rating: 3.5, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Lotus Donaucity", kueche: "Chinesisch", preis: "$$$", bezirk: 22,
    adresse: "Meißauergasse 19, 1220 Wien",
    rating: 3.8, oeffnung: { von: "11:00", bis: "00:00" } },
  // 23. Bezirk
  { name: "Trattoria Liesing", kueche: "Italienisch", preis: "$", bezirk: 23,
    adresse: "Breitenfurter Straße 42, 1230 Wien",
    rating: 4.1, oeffnung: { von: "11:30", bis: "23:00" } },
  { name: "Osteria Liesing", kueche: "Italienisch", preis: "$$", bezirk: 23,
    adresse: "Liesinger Platz 53, 1230 Wien",
    rating: 4.4, oeffnung: { von: "17:00", bis: "02:00" } },
  { name: "Ristorante Liesing", kueche: "Italienisch", preis: "$$$", bezirk: 23,
    adresse: "Rodauner Straße 4, 1230 Wien",
    rating: 4.7, oeffnung: { von: "08:00", bis: "18:00" } },
  { name: "Kaiserpalast Liesing", kueche: "Chinesisch", preis: "$", bezirk: 23,
    adresse: "Carlbergergasse 15, 1230 Wien",
    rating: 5.0, oeffnung: { von: "12:00", bis: "22:30" } },
  { name: "Jadegarten Liesing", kueche: "Chinesisch", preis: "$$$", bezirk: 23,
    adresse: "Perchtoldsdorfer Straße 26, 1230 Wien",
    rating: 3.6, oeffnung: { von: "11:00", bis: "00:00" } },
];
